---
- name: template for tap menu
  hosts: localhost
  become: true
  vars:
    tap1: "kolsch"
    tap2: "nose golbin"
    tap3: "creek park"
    mini_fridge: "galaxy ipa"

  tasks:
    - name: apply page template
      template:
        src: templates/index.html.j2
        dest: menu.html